- hosts: all
  become: true
  vars_files:
    - kubernetes_vars.yml
  roles:
    - common
    - "{{ container_runtime }}"
    - kubernetes-common
    - { role: master, when: "'master' in group_names" }
    - { role: worker, when: "'worker' in group_names" }
    - networking
    - addons
    - security