---
- hosts: all
  become: true
  vars_files:
    - kubernetes_vars.yml
  roles:
    - common
    - containerd
    - kubernetes-common

- hosts: masters
  become: true
  vars_files:
    - kubernetes_vars.yml
  roles:
    - master

- hosts: workers
  become: true
  vars_files:
    - kubernetes_vars.yml
  roles:
    - worker

- hosts: all
  become: true
  vars_files:
    - kubernetes_vars.yml
  roles:
    - networking
    - addons
    - security